name: deploy
on:
  push:
    branches:
      - "dev"

jobs:
  deploy:
    name: "Build & Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.17.0

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Connect to Oracle Cloud Subnet
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa tunnel@${{secrets.ORACLE_CLOUD_IP_ADDRESS}} 'connect-main'

      - name: Change Directory on Oracle Cloud
        run: |
          'cd /var/www/main_front && echo "Changed directory to /var/www/main_front"'
