name: "Update Pull Request"
on: pull_request

jobs:
  update_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Updater GitHub Action
        uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[a-z\d-_.\\/]+'
          head-branch-regex: 'zsd-\d+'
          body-template: |
            ### Fixes # (jira issue number if present)
            [%headbranch%](https://zenerate.atlassian.net/browse/%headbranch%)
          body-update-action: "prefix"
          body-newline-count: 2
          title-template: "[%headbranch%] "
